/*

This file was generated by the "C - Kessels engine grammar.h" template.

*/


wchar_t GrammarCharset0[7+1] = {
  9,
  10,
  11,
  12,
  13,
  32,
  160,
  0};
wchar_t GrammarCharset1[1+1] = {
  45,
  0};
wchar_t GrammarCharset2[1+1] = {
  33,
  0};
wchar_t GrammarCharset3[1+1] = {
  40,
  0};
wchar_t GrammarCharset4[1+1] = {
  41,
  0};
wchar_t GrammarCharset5[1+1] = {
  42,
  0};
wchar_t GrammarCharset6[1+1] = {
  47,
  0};
wchar_t GrammarCharset7[1+1] = {
  43,
  0};
wchar_t GrammarCharset8[1+1] = {
  61,
  0};
wchar_t GrammarCharset9[1+1] = {
  48,
  0};
wchar_t GrammarCharset10[51+1] = {
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  95,
  97,
  98,
  99,
  100,
  101,
  103,
  104,
  105,
  106,
  107,
  108,
  109,
  110,
  111,
  112,
  113,
  114,
  115,
  117,
  118,
  119,
  120,
  121,
  122,
  0};
wchar_t GrammarCharset11[1+1] = {
  34,
  0};
wchar_t GrammarCharset12[1+1] = {
  38,
  0};
wchar_t GrammarCharset13[9+1] = {
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  0};
wchar_t GrammarCharset14[1+1] = {
  60,
  0};
wchar_t GrammarCharset15[1+1] = {
  62,
  0};
wchar_t GrammarCharset16[1+1] = {
  102,
  0};
wchar_t GrammarCharset17[1+1] = {
  116,
  0};
wchar_t GrammarCharset18[1+1] = {
  124,
  0};
wchar_t GrammarCharset19[63+1] = {
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  95,
  97,
  98,
  99,
  100,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  109,
  110,
  111,
  112,
  113,
  114,
  115,
  116,
  117,
  118,
  119,
  120,
  121,
  122,
  0};
wchar_t GrammarCharset20[1+1] = {
  46,
  0};
wchar_t GrammarCharset21[53+1] = {
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  95,
  97,
  98,
  99,
  100,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  109,
  110,
  111,
  112,
  113,
  114,
  115,
  116,
  117,
  118,
  119,
  120,
  121,
  122,
  0};
wchar_t GrammarCharset22[95+1] = {
  9,
  32,
  33,
  35,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  63,
  64,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  93,
  94,
  95,
  96,
  97,
  98,
  99,
  100,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  109,
  110,
  111,
  112,
  113,
  114,
  115,
  116,
  117,
  118,
  119,
  120,
  121,
  122,
  123,
  124,
  125,
  126,
  160,
  0};
wchar_t GrammarCharset23[1+1] = {
  92,
  0};
wchar_t GrammarCharset24[96+1] = {
  32,
  33,
  34,
  35,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  63,
  64,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  97,
  98,
  99,
  100,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  109,
  110,
  111,
  112,
  113,
  114,
  115,
  116,
  117,
  118,
  119,
  120,
  121,
  122,
  123,
  124,
  125,
  126,
  160,
  0};
wchar_t GrammarCharset25[10+1] = {
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  0};
wchar_t GrammarCharset26[62+1] = {
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  95,
  98,
  99,
  100,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  109,
  110,
  111,
  112,
  113,
  114,
  115,
  116,
  117,
  118,
  119,
  120,
  121,
  122,
  0};
wchar_t GrammarCharset27[1+1] = {
  97,
  0};
wchar_t GrammarCharset28[62+1] = {
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  95,
  97,
  98,
  99,
  100,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  109,
  110,
  111,
  112,
  113,
  114,
  115,
  116,
  117,
  118,
  119,
  120,
  121,
  122,
  0};
wchar_t GrammarCharset29[1+1] = {
  108,
  0};
wchar_t GrammarCharset30[62+1] = {
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  95,
  97,
  98,
  99,
  100,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  109,
  110,
  111,
  112,
  113,
  114,
  116,
  117,
  118,
  119,
  120,
  121,
  122,
  0};
wchar_t GrammarCharset31[1+1] = {
  115,
  0};
wchar_t GrammarCharset32[62+1] = {
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  95,
  97,
  98,
  99,
  100,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  109,
  110,
  111,
  112,
  113,
  114,
  115,
  116,
  117,
  118,
  119,
  120,
  121,
  122,
  0};
wchar_t GrammarCharset33[1+1] = {
  101,
  0};
wchar_t GrammarCharset34[62+1] = {
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  95,
  97,
  98,
  99,
  100,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  109,
  110,
  111,
  112,
  113,
  115,
  116,
  117,
  118,
  119,
  120,
  121,
  122,
  0};
wchar_t GrammarCharset35[1+1] = {
  114,
  0};
wchar_t GrammarCharset36[62+1] = {
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  95,
  97,
  98,
  99,
  100,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  109,
  110,
  111,
  112,
  113,
  114,
  115,
  116,
  118,
  119,
  120,
  121,
  122,
  0};
wchar_t GrammarCharset37[1+1] = {
  117,
  0};



struct DfaEdgeStruct GrammarDfaEdgeArray0[19+1] = {
  {1,GrammarCharset0},
  {2,GrammarCharset1},
  {3,GrammarCharset2},
  {5,GrammarCharset3},
  {6,GrammarCharset4},
  {7,GrammarCharset5},
  {8,GrammarCharset6},
  {9,GrammarCharset7},
  {10,GrammarCharset8},
  {12,GrammarCharset9},
  {13,GrammarCharset10},
  {18,GrammarCharset11},
  {23,GrammarCharset12},
  {25,GrammarCharset13},
  {27,GrammarCharset14},
  {29,GrammarCharset15},
  {31,GrammarCharset16},
  {36,GrammarCharset17},
  {40,GrammarCharset18},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray1[1+1] = {
  {1,GrammarCharset0},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray2[0+1] = {
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray3[1+1] = {
  {4,GrammarCharset8},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray4[0+1] = {
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray5[0+1] = {
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray6[0+1] = {
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray7[0+1] = {
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray8[0+1] = {
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray9[0+1] = {
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray10[1+1] = {
  {11,GrammarCharset8},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray11[0+1] = {
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray12[0+1] = {
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray13[2+1] = {
  {14,GrammarCharset19},
  {15,GrammarCharset20},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray14[2+1] = {
  {14,GrammarCharset19},
  {15,GrammarCharset20},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray15[1+1] = {
  {16,GrammarCharset21},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray16[2+1] = {
  {15,GrammarCharset20},
  {17,GrammarCharset19},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray17[2+1] = {
  {15,GrammarCharset20},
  {17,GrammarCharset19},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray18[3+1] = {
  {19,GrammarCharset22},
  {20,GrammarCharset23},
  {22,GrammarCharset11},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray19[3+1] = {
  {19,GrammarCharset22},
  {20,GrammarCharset23},
  {22,GrammarCharset11},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray20[1+1] = {
  {21,GrammarCharset24},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray21[3+1] = {
  {19,GrammarCharset22},
  {20,GrammarCharset23},
  {22,GrammarCharset11},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray22[0+1] = {
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray23[1+1] = {
  {24,GrammarCharset12},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray24[0+1] = {
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray25[1+1] = {
  {26,GrammarCharset25},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray26[1+1] = {
  {26,GrammarCharset25},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray27[1+1] = {
  {28,GrammarCharset8},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray28[0+1] = {
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray29[1+1] = {
  {30,GrammarCharset8},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray30[0+1] = {
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray31[3+1] = {
  {14,GrammarCharset26},
  {15,GrammarCharset20},
  {32,GrammarCharset27},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray32[3+1] = {
  {14,GrammarCharset28},
  {15,GrammarCharset20},
  {33,GrammarCharset29},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray33[3+1] = {
  {14,GrammarCharset30},
  {15,GrammarCharset20},
  {34,GrammarCharset31},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray34[3+1] = {
  {14,GrammarCharset32},
  {15,GrammarCharset20},
  {35,GrammarCharset33},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray35[2+1] = {
  {14,GrammarCharset19},
  {15,GrammarCharset20},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray36[3+1] = {
  {14,GrammarCharset34},
  {15,GrammarCharset20},
  {37,GrammarCharset35},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray37[3+1] = {
  {14,GrammarCharset36},
  {15,GrammarCharset20},
  {38,GrammarCharset37},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray38[3+1] = {
  {14,GrammarCharset32},
  {15,GrammarCharset20},
  {39,GrammarCharset33},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray39[2+1] = {
  {14,GrammarCharset19},
  {15,GrammarCharset20},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray40[1+1] = {
  {41,GrammarCharset18},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray41[0+1] = {
  {-1,NULL}};



int GrammarRuleSymbolArray0[1+1] = {
  25,
  -1};
int GrammarRuleSymbolArray1[3+1] = {
  25,
  12,
  26,
  -1};
int GrammarRuleSymbolArray2[3+1] = {
  25,
  6,
  26,
  -1};
int GrammarRuleSymbolArray3[1+1] = {
  26,
  -1};
int GrammarRuleSymbolArray4[3+1] = {
  26,
  17,
  23,
  -1};
int GrammarRuleSymbolArray5[3+1] = {
  26,
  14,
  23,
  -1};
int GrammarRuleSymbolArray6[3+1] = {
  26,
  15,
  23,
  -1};
int GrammarRuleSymbolArray7[3+1] = {
  26,
  18,
  23,
  -1};
int GrammarRuleSymbolArray8[3+1] = {
  26,
  16,
  23,
  -1};
int GrammarRuleSymbolArray9[3+1] = {
  26,
  4,
  23,
  -1};
int GrammarRuleSymbolArray10[1+1] = {
  23,
  -1};
int GrammarRuleSymbolArray11[3+1] = {
  23,
  13,
  27,
  -1};
int GrammarRuleSymbolArray12[3+1] = {
  23,
  3,
  27,
  -1};
int GrammarRuleSymbolArray13[1+1] = {
  27,
  -1};
int GrammarRuleSymbolArray14[3+1] = {
  27,
  9,
  28,
  -1};
int GrammarRuleSymbolArray15[3+1] = {
  27,
  10,
  28,
  -1};
int GrammarRuleSymbolArray16[1+1] = {
  24,
  -1};
int GrammarRuleSymbolArray17[3+1] = {
  24,
  5,
  28,
  -1};
int GrammarRuleSymbolArray18[3+1] = {
  24,
  11,
  28,
  -1};
int GrammarRuleSymbolArray19[1+1] = {
  28,
  -1};
int GrammarRuleSymbolArray20[2+1] = {
  3,
  30,
  -1};
int GrammarRuleSymbolArray21[1+1] = {
  30,
  -1};
int GrammarRuleSymbolArray22[1+1] = {
  21,
  -1};
int GrammarRuleSymbolArray23[1+1] = {
  22,
  -1};
int GrammarRuleSymbolArray24[1+1] = {
  20,
  -1};
int GrammarRuleSymbolArray25[3+1] = {
  7,
  26,
  8,
  -1};
int GrammarRuleSymbolArray26[1+1] = {
  19,
  -1};


struct ActionStruct GrammarLalrActionArray0[14+1] = {
  {3,1,1},
  {7,1,2},
  {19,1,3},
  {20,1,4},
  {21,1,5},
  {22,1,6},
  {23,3,7},
  {24,3,8},
  {25,3,9},
  {26,3,10},
  {27,3,11},
  {28,3,12},
  {29,3,13},
  {30,3,14},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray1[6+1] = {
  {7,1,2},
  {19,1,3},
  {20,1,4},
  {21,1,5},
  {22,1,6},
  {30,3,15},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray2[12+1] = {
  {3,1,1},
  {7,1,2},
  {19,1,3},
  {20,1,4},
  {21,1,5},
  {22,1,6},
  {23,3,7},
  {24,3,8},
  {26,3,16},
  {27,3,11},
  {28,3,12},
  {30,3,14},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray3[16+1] = {
  {0,2,26},
  {3,2,26},
  {4,2,26},
  {5,2,26},
  {6,2,26},
  {8,2,26},
  {9,2,26},
  {10,2,26},
  {11,2,26},
  {12,2,26},
  {13,2,26},
  {14,2,26},
  {15,2,26},
  {16,2,26},
  {17,2,26},
  {18,2,26},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray4[16+1] = {
  {0,2,24},
  {3,2,24},
  {4,2,24},
  {5,2,24},
  {6,2,24},
  {8,2,24},
  {9,2,24},
  {10,2,24},
  {11,2,24},
  {12,2,24},
  {13,2,24},
  {14,2,24},
  {15,2,24},
  {16,2,24},
  {17,2,24},
  {18,2,24},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray5[16+1] = {
  {0,2,22},
  {3,2,22},
  {4,2,22},
  {5,2,22},
  {6,2,22},
  {8,2,22},
  {9,2,22},
  {10,2,22},
  {11,2,22},
  {12,2,22},
  {13,2,22},
  {14,2,22},
  {15,2,22},
  {16,2,22},
  {17,2,22},
  {18,2,22},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray6[16+1] = {
  {0,2,23},
  {3,2,23},
  {4,2,23},
  {5,2,23},
  {6,2,23},
  {8,2,23},
  {9,2,23},
  {10,2,23},
  {11,2,23},
  {12,2,23},
  {13,2,23},
  {14,2,23},
  {15,2,23},
  {16,2,23},
  {17,2,23},
  {18,2,23},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray7[12+1] = {
  {3,1,17},
  {13,1,18},
  {0,2,10},
  {4,2,10},
  {6,2,10},
  {8,2,10},
  {12,2,10},
  {14,2,10},
  {15,2,10},
  {16,2,10},
  {17,2,10},
  {18,2,10},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray8[16+1] = {
  {5,1,19},
  {11,1,20},
  {0,2,16},
  {3,2,16},
  {4,2,16},
  {6,2,16},
  {8,2,16},
  {9,2,16},
  {10,2,16},
  {12,2,16},
  {13,2,16},
  {14,2,16},
  {15,2,16},
  {16,2,16},
  {17,2,16},
  {18,2,16},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray9[3+1] = {
  {6,1,21},
  {12,1,22},
  {0,2,0},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray10[9+1] = {
  {4,1,23},
  {14,1,24},
  {15,1,25},
  {16,1,26},
  {17,1,27},
  {18,1,28},
  {0,2,3},
  {6,2,3},
  {12,2,3},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray11[14+1] = {
  {9,1,29},
  {10,1,30},
  {0,2,13},
  {3,2,13},
  {4,2,13},
  {6,2,13},
  {8,2,13},
  {12,2,13},
  {13,2,13},
  {14,2,13},
  {15,2,13},
  {16,2,13},
  {17,2,13},
  {18,2,13},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray12[16+1] = {
  {0,2,19},
  {3,2,19},
  {4,2,19},
  {5,2,19},
  {6,2,19},
  {8,2,19},
  {9,2,19},
  {10,2,19},
  {11,2,19},
  {12,2,19},
  {13,2,19},
  {14,2,19},
  {15,2,19},
  {16,2,19},
  {17,2,19},
  {18,2,19},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray13[1+1] = {
  {0,4,0},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray14[16+1] = {
  {0,2,21},
  {3,2,21},
  {4,2,21},
  {5,2,21},
  {6,2,21},
  {8,2,21},
  {9,2,21},
  {10,2,21},
  {11,2,21},
  {12,2,21},
  {13,2,21},
  {14,2,21},
  {15,2,21},
  {16,2,21},
  {17,2,21},
  {18,2,21},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray15[16+1] = {
  {0,2,20},
  {3,2,20},
  {4,2,20},
  {5,2,20},
  {6,2,20},
  {8,2,20},
  {9,2,20},
  {10,2,20},
  {11,2,20},
  {12,2,20},
  {13,2,20},
  {14,2,20},
  {15,2,20},
  {16,2,20},
  {17,2,20},
  {18,2,20},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray16[7+1] = {
  {4,1,23},
  {8,1,31},
  {14,1,24},
  {15,1,25},
  {16,1,26},
  {17,1,27},
  {18,1,28},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray17[10+1] = {
  {3,1,1},
  {7,1,2},
  {19,1,3},
  {20,1,4},
  {21,1,5},
  {22,1,6},
  {24,3,8},
  {27,3,32},
  {28,3,12},
  {30,3,14},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray18[10+1] = {
  {3,1,1},
  {7,1,2},
  {19,1,3},
  {20,1,4},
  {21,1,5},
  {22,1,6},
  {24,3,8},
  {27,3,33},
  {28,3,12},
  {30,3,14},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray19[8+1] = {
  {3,1,1},
  {7,1,2},
  {19,1,3},
  {20,1,4},
  {21,1,5},
  {22,1,6},
  {28,3,34},
  {30,3,14},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray20[8+1] = {
  {3,1,1},
  {7,1,2},
  {19,1,3},
  {20,1,4},
  {21,1,5},
  {22,1,6},
  {28,3,35},
  {30,3,14},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray21[12+1] = {
  {3,1,1},
  {7,1,2},
  {19,1,3},
  {20,1,4},
  {21,1,5},
  {22,1,6},
  {23,3,7},
  {24,3,8},
  {26,3,36},
  {27,3,11},
  {28,3,12},
  {30,3,14},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray22[12+1] = {
  {3,1,1},
  {7,1,2},
  {19,1,3},
  {20,1,4},
  {21,1,5},
  {22,1,6},
  {23,3,7},
  {24,3,8},
  {26,3,37},
  {27,3,11},
  {28,3,12},
  {30,3,14},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray23[11+1] = {
  {3,1,1},
  {7,1,2},
  {19,1,3},
  {20,1,4},
  {21,1,5},
  {22,1,6},
  {23,3,38},
  {24,3,8},
  {27,3,11},
  {28,3,12},
  {30,3,14},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray24[11+1] = {
  {3,1,1},
  {7,1,2},
  {19,1,3},
  {20,1,4},
  {21,1,5},
  {22,1,6},
  {23,3,39},
  {24,3,8},
  {27,3,11},
  {28,3,12},
  {30,3,14},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray25[11+1] = {
  {3,1,1},
  {7,1,2},
  {19,1,3},
  {20,1,4},
  {21,1,5},
  {22,1,6},
  {23,3,40},
  {24,3,8},
  {27,3,11},
  {28,3,12},
  {30,3,14},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray26[11+1] = {
  {3,1,1},
  {7,1,2},
  {19,1,3},
  {20,1,4},
  {21,1,5},
  {22,1,6},
  {23,3,41},
  {24,3,8},
  {27,3,11},
  {28,3,12},
  {30,3,14},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray27[11+1] = {
  {3,1,1},
  {7,1,2},
  {19,1,3},
  {20,1,4},
  {21,1,5},
  {22,1,6},
  {23,3,42},
  {24,3,8},
  {27,3,11},
  {28,3,12},
  {30,3,14},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray28[11+1] = {
  {3,1,1},
  {7,1,2},
  {19,1,3},
  {20,1,4},
  {21,1,5},
  {22,1,6},
  {23,3,43},
  {24,3,8},
  {27,3,11},
  {28,3,12},
  {30,3,14},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray29[8+1] = {
  {3,1,1},
  {7,1,2},
  {19,1,3},
  {20,1,4},
  {21,1,5},
  {22,1,6},
  {28,3,44},
  {30,3,14},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray30[8+1] = {
  {3,1,1},
  {7,1,2},
  {19,1,3},
  {20,1,4},
  {21,1,5},
  {22,1,6},
  {28,3,45},
  {30,3,14},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray31[16+1] = {
  {0,2,25},
  {3,2,25},
  {4,2,25},
  {5,2,25},
  {6,2,25},
  {8,2,25},
  {9,2,25},
  {10,2,25},
  {11,2,25},
  {12,2,25},
  {13,2,25},
  {14,2,25},
  {15,2,25},
  {16,2,25},
  {17,2,25},
  {18,2,25},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray32[14+1] = {
  {9,1,29},
  {10,1,30},
  {0,2,12},
  {3,2,12},
  {4,2,12},
  {6,2,12},
  {8,2,12},
  {12,2,12},
  {13,2,12},
  {14,2,12},
  {15,2,12},
  {16,2,12},
  {17,2,12},
  {18,2,12},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray33[14+1] = {
  {9,1,29},
  {10,1,30},
  {0,2,11},
  {3,2,11},
  {4,2,11},
  {6,2,11},
  {8,2,11},
  {12,2,11},
  {13,2,11},
  {14,2,11},
  {15,2,11},
  {16,2,11},
  {17,2,11},
  {18,2,11},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray34[16+1] = {
  {0,2,17},
  {3,2,17},
  {4,2,17},
  {5,2,17},
  {6,2,17},
  {8,2,17},
  {9,2,17},
  {10,2,17},
  {11,2,17},
  {12,2,17},
  {13,2,17},
  {14,2,17},
  {15,2,17},
  {16,2,17},
  {17,2,17},
  {18,2,17},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray35[16+1] = {
  {0,2,18},
  {3,2,18},
  {4,2,18},
  {5,2,18},
  {6,2,18},
  {8,2,18},
  {9,2,18},
  {10,2,18},
  {11,2,18},
  {12,2,18},
  {13,2,18},
  {14,2,18},
  {15,2,18},
  {16,2,18},
  {17,2,18},
  {18,2,18},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray36[9+1] = {
  {4,1,23},
  {14,1,24},
  {15,1,25},
  {16,1,26},
  {17,1,27},
  {18,1,28},
  {0,2,2},
  {6,2,2},
  {12,2,2},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray37[9+1] = {
  {4,1,23},
  {14,1,24},
  {15,1,25},
  {16,1,26},
  {17,1,27},
  {18,1,28},
  {0,2,1},
  {6,2,1},
  {12,2,1},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray38[12+1] = {
  {3,1,17},
  {13,1,18},
  {0,2,9},
  {4,2,9},
  {6,2,9},
  {8,2,9},
  {12,2,9},
  {14,2,9},
  {15,2,9},
  {16,2,9},
  {17,2,9},
  {18,2,9},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray39[12+1] = {
  {3,1,17},
  {13,1,18},
  {0,2,5},
  {4,2,5},
  {6,2,5},
  {8,2,5},
  {12,2,5},
  {14,2,5},
  {15,2,5},
  {16,2,5},
  {17,2,5},
  {18,2,5},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray40[12+1] = {
  {3,1,17},
  {13,1,18},
  {0,2,6},
  {4,2,6},
  {6,2,6},
  {8,2,6},
  {12,2,6},
  {14,2,6},
  {15,2,6},
  {16,2,6},
  {17,2,6},
  {18,2,6},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray41[12+1] = {
  {3,1,17},
  {13,1,18},
  {0,2,8},
  {4,2,8},
  {6,2,8},
  {8,2,8},
  {12,2,8},
  {14,2,8},
  {15,2,8},
  {16,2,8},
  {17,2,8},
  {18,2,8},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray42[12+1] = {
  {3,1,17},
  {13,1,18},
  {0,2,4},
  {4,2,4},
  {6,2,4},
  {8,2,4},
  {12,2,4},
  {14,2,4},
  {15,2,4},
  {16,2,4},
  {17,2,4},
  {18,2,4},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray43[12+1] = {
  {3,1,17},
  {13,1,18},
  {0,2,7},
  {4,2,7},
  {6,2,7},
  {8,2,7},
  {12,2,7},
  {14,2,7},
  {15,2,7},
  {16,2,7},
  {17,2,7},
  {18,2,7},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray44[14+1] = {
  {0,2,14},
  {3,2,14},
  {4,2,14},
  {6,2,14},
  {8,2,14},
  {9,2,14},
  {10,2,14},
  {12,2,14},
  {13,2,14},
  {14,2,14},
  {15,2,14},
  {16,2,14},
  {17,2,14},
  {18,2,14},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray45[14+1] = {
  {0,2,15},
  {3,2,15},
  {4,2,15},
  {6,2,15},
  {8,2,15},
  {9,2,15},
  {10,2,15},
  {12,2,15},
  {13,2,15},
  {14,2,15},
  {15,2,15},
  {16,2,15},
  {17,2,15},
  {18,2,15},
  {-1,-1,-1}};



/*
struct SymbolStruct {
  short Kind;
  char *Name;
  };
*/
struct SymbolStruct GrammarSymbolArray[31] = {
  /*  0 */   {3,"EOF"},
  /*  1 */   {7,"Error"},
  /*  2 */   {2,"Whitespace"},
  /*  3 */   {1,"-"},
  /*  4 */   {1,"!="},
  /*  5 */   {1,"&"},
  /*  6 */   {1,"&&"},
  /*  7 */   {1,"("},
  /*  8 */   {1,")"},
  /*  9 */   {1,"*"},
  /* 10 */   {1,"/"},
  /* 11 */   {1,"|"},
  /* 12 */   {1,"||"},
  /* 13 */   {1,"+"},
  /* 14 */   {1,"<"},
  /* 15 */   {1,"<="},
  /* 16 */   {1,"=="},
  /* 17 */   {1,">"},
  /* 18 */   {1,">="},
  /* 19 */   {1,"BooleanLiteral"},
  /* 20 */   {1,"DecimalNumber"},
  /* 21 */   {1,"Identifier"},
  /* 22 */   {1,"StringLiteral"},
  /* 23 */   {0,"Add Exp"},
  /* 24 */   {0,"Bit Exp"},
  /* 25 */   {0,"Boolean Exp"},
  /* 26 */   {0,"Cmp Exp"},
  /* 27 */   {0,"Mult Exp"},
  /* 28 */   {0,"Negate Exp"},
  /* 29 */   {0,"Program"},
  /* 30 */   {0,"Value"} 
  };



/*
struct DfaEdgeStruct {
  int TargetState;
  char *CharacterSet;
  };
struct DfaStateStruct {
  int AcceptSymbol;
  int EdgeCount;
  struct DfaEdgeStruct *Edges;
  };
*/
struct DfaStateStruct GrammarDfaStateArray[42+1] = {
  /* 0 */    {-1,19,GrammarDfaEdgeArray0},
  /* 1 */    {2,1,GrammarDfaEdgeArray1},
  /* 2 */    {3,0,GrammarDfaEdgeArray2},
  /* 3 */    {-1,1,GrammarDfaEdgeArray3},
  /* 4 */    {4,0,GrammarDfaEdgeArray4},
  /* 5 */    {7,0,GrammarDfaEdgeArray5},
  /* 6 */    {8,0,GrammarDfaEdgeArray6},
  /* 7 */    {9,0,GrammarDfaEdgeArray7},
  /* 8 */    {10,0,GrammarDfaEdgeArray8},
  /* 9 */    {13,0,GrammarDfaEdgeArray9},
  /* 10 */    {-1,1,GrammarDfaEdgeArray10},
  /* 11 */    {16,0,GrammarDfaEdgeArray11},
  /* 12 */    {20,0,GrammarDfaEdgeArray12},
  /* 13 */    {21,2,GrammarDfaEdgeArray13},
  /* 14 */    {21,2,GrammarDfaEdgeArray14},
  /* 15 */    {-1,1,GrammarDfaEdgeArray15},
  /* 16 */    {21,2,GrammarDfaEdgeArray16},
  /* 17 */    {21,2,GrammarDfaEdgeArray17},
  /* 18 */    {-1,3,GrammarDfaEdgeArray18},
  /* 19 */    {-1,3,GrammarDfaEdgeArray19},
  /* 20 */    {-1,1,GrammarDfaEdgeArray20},
  /* 21 */    {-1,3,GrammarDfaEdgeArray21},
  /* 22 */    {22,0,GrammarDfaEdgeArray22},
  /* 23 */    {5,1,GrammarDfaEdgeArray23},
  /* 24 */    {6,0,GrammarDfaEdgeArray24},
  /* 25 */    {20,1,GrammarDfaEdgeArray25},
  /* 26 */    {20,1,GrammarDfaEdgeArray26},
  /* 27 */    {14,1,GrammarDfaEdgeArray27},
  /* 28 */    {15,0,GrammarDfaEdgeArray28},
  /* 29 */    {17,1,GrammarDfaEdgeArray29},
  /* 30 */    {18,0,GrammarDfaEdgeArray30},
  /* 31 */    {21,3,GrammarDfaEdgeArray31},
  /* 32 */    {21,3,GrammarDfaEdgeArray32},
  /* 33 */    {21,3,GrammarDfaEdgeArray33},
  /* 34 */    {21,3,GrammarDfaEdgeArray34},
  /* 35 */    {19,2,GrammarDfaEdgeArray35},
  /* 36 */    {21,3,GrammarDfaEdgeArray36},
  /* 37 */    {21,3,GrammarDfaEdgeArray37},
  /* 38 */    {21,3,GrammarDfaEdgeArray38},
  /* 39 */    {19,2,GrammarDfaEdgeArray39},
  /* 40 */    {11,1,GrammarDfaEdgeArray40},
  /* 41 */    {12,0,GrammarDfaEdgeArray41},
  {-1,-1,NULL}};



/*
struct RuleStruct {
  int Head;
  int SymbolsCount;
  int *Symbols;
  char *Description;
  };
*/
struct RuleStruct GrammarRuleArray[27] = {
  /*  0 */   {29,1,GrammarRuleSymbolArray0,"<Program> ::= <Boolean Exp>"},
  /*  1 */   {25,3,GrammarRuleSymbolArray1,"<Boolean Exp> ::= <Boolean Exp> '||' <Cmp Exp>"},
  /*  2 */   {25,3,GrammarRuleSymbolArray2,"<Boolean Exp> ::= <Boolean Exp> '&&' <Cmp Exp>"},
  /*  3 */   {25,1,GrammarRuleSymbolArray3,"<Boolean Exp> ::= <Cmp Exp>"},
  /*  4 */   {26,3,GrammarRuleSymbolArray4,"<Cmp Exp> ::= <Cmp Exp> '>' <Add Exp>"},
  /*  5 */   {26,3,GrammarRuleSymbolArray5,"<Cmp Exp> ::= <Cmp Exp> '<' <Add Exp>"},
  /*  6 */   {26,3,GrammarRuleSymbolArray6,"<Cmp Exp> ::= <Cmp Exp> '<=' <Add Exp>"},
  /*  7 */   {26,3,GrammarRuleSymbolArray7,"<Cmp Exp> ::= <Cmp Exp> '>=' <Add Exp>"},
  /*  8 */   {26,3,GrammarRuleSymbolArray8,"<Cmp Exp> ::= <Cmp Exp> '==' <Add Exp>"},
  /*  9 */   {26,3,GrammarRuleSymbolArray9,"<Cmp Exp> ::= <Cmp Exp> '!=' <Add Exp>"},
  /* 10 */   {26,1,GrammarRuleSymbolArray10,"<Cmp Exp> ::= <Add Exp>"},
  /* 11 */   {23,3,GrammarRuleSymbolArray11,"<Add Exp> ::= <Add Exp> '+' <Mult Exp>"},
  /* 12 */   {23,3,GrammarRuleSymbolArray12,"<Add Exp> ::= <Add Exp> '-' <Mult Exp>"},
  /* 13 */   {23,1,GrammarRuleSymbolArray13,"<Add Exp> ::= <Mult Exp>"},
  /* 14 */   {27,3,GrammarRuleSymbolArray14,"<Mult Exp> ::= <Mult Exp> '*' <Negate Exp>"},
  /* 15 */   {27,3,GrammarRuleSymbolArray15,"<Mult Exp> ::= <Mult Exp> '/' <Negate Exp>"},
  /* 16 */   {27,1,GrammarRuleSymbolArray16,"<Mult Exp> ::= <Bit Exp>"},
  /* 17 */   {24,3,GrammarRuleSymbolArray17,"<Bit Exp> ::= <Bit Exp> '&' <Negate Exp>"},
  /* 18 */   {24,3,GrammarRuleSymbolArray18,"<Bit Exp> ::= <Bit Exp> '|' <Negate Exp>"},
  /* 19 */   {24,1,GrammarRuleSymbolArray19,"<Bit Exp> ::= <Negate Exp>"},
  /* 20 */   {28,2,GrammarRuleSymbolArray20,"<Negate Exp> ::= '-' <Value>"},
  /* 21 */   {28,1,GrammarRuleSymbolArray21,"<Negate Exp> ::= <Value>"},
  /* 22 */   {30,1,GrammarRuleSymbolArray22,"<Value> ::= Identifier"},
  /* 23 */   {30,1,GrammarRuleSymbolArray23,"<Value> ::= StringLiteral"},
  /* 24 */   {30,1,GrammarRuleSymbolArray24,"<Value> ::= DecimalNumber"},
  /* 25 */   {30,3,GrammarRuleSymbolArray25,"<Value> ::= '(' <Cmp Exp> ')'"},
  /* 26 */   {30,1,GrammarRuleSymbolArray26,"<Value> ::= BooleanLiteral"} 
  };



/*
struct ActionStruct {
  int Entry;
  short Action;
  int Target;
  };
struct LalrStateStruct {
  int ActionCount;
  struct ActionStruct *Actions;
  };
*/
struct LalrStateStruct GrammarLalrStateArray[46+1] = {
  /* 0 */   {14,GrammarLalrActionArray0},
  /* 1 */   {6,GrammarLalrActionArray1},
  /* 2 */   {12,GrammarLalrActionArray2},
  /* 3 */   {16,GrammarLalrActionArray3},
  /* 4 */   {16,GrammarLalrActionArray4},
  /* 5 */   {16,GrammarLalrActionArray5},
  /* 6 */   {16,GrammarLalrActionArray6},
  /* 7 */   {12,GrammarLalrActionArray7},
  /* 8 */   {16,GrammarLalrActionArray8},
  /* 9 */   {3,GrammarLalrActionArray9},
  /* 10 */   {9,GrammarLalrActionArray10},
  /* 11 */   {14,GrammarLalrActionArray11},
  /* 12 */   {16,GrammarLalrActionArray12},
  /* 13 */   {1,GrammarLalrActionArray13},
  /* 14 */   {16,GrammarLalrActionArray14},
  /* 15 */   {16,GrammarLalrActionArray15},
  /* 16 */   {7,GrammarLalrActionArray16},
  /* 17 */   {10,GrammarLalrActionArray17},
  /* 18 */   {10,GrammarLalrActionArray18},
  /* 19 */   {8,GrammarLalrActionArray19},
  /* 20 */   {8,GrammarLalrActionArray20},
  /* 21 */   {12,GrammarLalrActionArray21},
  /* 22 */   {12,GrammarLalrActionArray22},
  /* 23 */   {11,GrammarLalrActionArray23},
  /* 24 */   {11,GrammarLalrActionArray24},
  /* 25 */   {11,GrammarLalrActionArray25},
  /* 26 */   {11,GrammarLalrActionArray26},
  /* 27 */   {11,GrammarLalrActionArray27},
  /* 28 */   {11,GrammarLalrActionArray28},
  /* 29 */   {8,GrammarLalrActionArray29},
  /* 30 */   {8,GrammarLalrActionArray30},
  /* 31 */   {16,GrammarLalrActionArray31},
  /* 32 */   {14,GrammarLalrActionArray32},
  /* 33 */   {14,GrammarLalrActionArray33},
  /* 34 */   {16,GrammarLalrActionArray34},
  /* 35 */   {16,GrammarLalrActionArray35},
  /* 36 */   {9,GrammarLalrActionArray36},
  /* 37 */   {9,GrammarLalrActionArray37},
  /* 38 */   {12,GrammarLalrActionArray38},
  /* 39 */   {12,GrammarLalrActionArray39},
  /* 40 */   {12,GrammarLalrActionArray40},
  /* 41 */   {12,GrammarLalrActionArray41},
  /* 42 */   {12,GrammarLalrActionArray42},
  /* 43 */   {12,GrammarLalrActionArray43},
  /* 44 */   {14,GrammarLalrActionArray44},
  /* 45 */   {14,GrammarLalrActionArray45},
  {-1,NULL}};



/*
struct GrammarStruct {
  char CaseSensitive;
  int InitialSymbol;
  int InitialDfaState;
  int InitialLalrState;
  int SymbolCount;
  struct SymbolStruct *SymbolArray;
  int RuleCount;
  struct RuleStruct *RuleArray;
  int DfaStateCount;
  struct DfaStateStruct *DfaArray;
  int LalrStateCount;
  struct LalrStateStruct *LalrArray;
  };
*/
struct GrammarStruct Grammar = {
  /* CaseSensitive */      true,
  /* InitialSymbol */      29,
  /* InitialDfaState */    0,
  /* InitialLalrState */   0,
  /* SymbolCount */        31,
  /* SymbolArray */        GrammarSymbolArray,
  /* RuleCount */          27,
  /* RuleArray */          GrammarRuleArray,
  /* DfaStateCount */      42,
  /* DfaArray */           GrammarDfaStateArray,
  /* LalrStateCount */     46,
  /* LalrArray */          GrammarLalrStateArray
  };
