/*

This file was generated by the "C - Kessels engine grammar.h" template.

*/


wchar_t GrammarCharset0[7+1] = {
  9,
  10,
  11,
  12,
  13,
  32,
  160,
  0};
wchar_t GrammarCharset1[1+1] = {
  45,
  0};
wchar_t GrammarCharset2[1+1] = {
  40,
  0};
wchar_t GrammarCharset3[1+1] = {
  41,
  0};
wchar_t GrammarCharset4[1+1] = {
  42,
  0};
wchar_t GrammarCharset5[1+1] = {
  47,
  0};
wchar_t GrammarCharset6[1+1] = {
  43,
  0};
wchar_t GrammarCharset7[1+1] = {
  61,
  0};
wchar_t GrammarCharset8[53+1] = {
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  95,
  97,
  98,
  99,
  100,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  109,
  110,
  111,
  112,
  113,
  114,
  115,
  116,
  117,
  118,
  119,
  120,
  121,
  122,
  0};
wchar_t GrammarCharset9[1+1] = {
  34,
  0};
wchar_t GrammarCharset10[1+1] = {
  60,
  0};
wchar_t GrammarCharset11[1+1] = {
  62,
  0};
wchar_t GrammarCharset12[63+1] = {
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  95,
  97,
  98,
  99,
  100,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  109,
  110,
  111,
  112,
  113,
  114,
  115,
  116,
  117,
  118,
  119,
  120,
  121,
  122,
  0};
wchar_t GrammarCharset13[95+1] = {
  9,
  32,
  33,
  35,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  63,
  64,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  93,
  94,
  95,
  96,
  97,
  98,
  99,
  100,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  109,
  110,
  111,
  112,
  113,
  114,
  115,
  116,
  117,
  118,
  119,
  120,
  121,
  122,
  123,
  124,
  125,
  126,
  160,
  0};
wchar_t GrammarCharset14[1+1] = {
  92,
  0};
wchar_t GrammarCharset15[96+1] = {
  32,
  33,
  34,
  35,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  63,
  64,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  97,
  98,
  99,
  100,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  109,
  110,
  111,
  112,
  113,
  114,
  115,
  116,
  117,
  118,
  119,
  120,
  121,
  122,
  123,
  124,
  125,
  126,
  160,
  0};



struct DfaEdgeStruct GrammarDfaEdgeArray0[12+1] = {
  {1,GrammarCharset0},
  {2,GrammarCharset1},
  {3,GrammarCharset2},
  {4,GrammarCharset3},
  {5,GrammarCharset4},
  {6,GrammarCharset5},
  {7,GrammarCharset6},
  {8,GrammarCharset7},
  {10,GrammarCharset8},
  {12,GrammarCharset9},
  {17,GrammarCharset10},
  {20,GrammarCharset11},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray1[1+1] = {
  {1,GrammarCharset0},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray2[0+1] = {
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray3[0+1] = {
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray4[0+1] = {
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray5[0+1] = {
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray6[0+1] = {
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray7[0+1] = {
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray8[1+1] = {
  {9,GrammarCharset7},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray9[0+1] = {
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray10[1+1] = {
  {11,GrammarCharset12},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray11[1+1] = {
  {11,GrammarCharset12},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray12[3+1] = {
  {13,GrammarCharset13},
  {14,GrammarCharset14},
  {16,GrammarCharset9},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray13[3+1] = {
  {13,GrammarCharset13},
  {14,GrammarCharset14},
  {16,GrammarCharset9},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray14[1+1] = {
  {15,GrammarCharset15},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray15[3+1] = {
  {13,GrammarCharset13},
  {14,GrammarCharset14},
  {16,GrammarCharset9},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray16[0+1] = {
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray17[2+1] = {
  {18,GrammarCharset7},
  {19,GrammarCharset11},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray18[0+1] = {
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray19[0+1] = {
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray20[1+1] = {
  {21,GrammarCharset7},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray21[0+1] = {
  {-1,NULL}};



int GrammarRuleSymbolArray0[1+1] = {
  18,
  -1};
int GrammarRuleSymbolArray1[3+1] = {
  18,
  13,
  17,
  -1};
int GrammarRuleSymbolArray2[3+1] = {
  18,
  9,
  17,
  -1};
int GrammarRuleSymbolArray3[3+1] = {
  18,
  10,
  17,
  -1};
int GrammarRuleSymbolArray4[3+1] = {
  18,
  14,
  17,
  -1};
int GrammarRuleSymbolArray5[3+1] = {
  18,
  12,
  17,
  -1};
int GrammarRuleSymbolArray6[3+1] = {
  18,
  11,
  17,
  -1};
int GrammarRuleSymbolArray7[1+1] = {
  17,
  -1};
int GrammarRuleSymbolArray8[3+1] = {
  17,
  8,
  19,
  -1};
int GrammarRuleSymbolArray9[3+1] = {
  17,
  3,
  19,
  -1};
int GrammarRuleSymbolArray10[1+1] = {
  19,
  -1};
int GrammarRuleSymbolArray11[3+1] = {
  19,
  6,
  20,
  -1};
int GrammarRuleSymbolArray12[3+1] = {
  19,
  7,
  20,
  -1};
int GrammarRuleSymbolArray13[1+1] = {
  20,
  -1};
int GrammarRuleSymbolArray14[2+1] = {
  3,
  22,
  -1};
int GrammarRuleSymbolArray15[1+1] = {
  22,
  -1};
int GrammarRuleSymbolArray16[1+1] = {
  15,
  -1};
int GrammarRuleSymbolArray17[3+1] = {
  4,
  18,
  5,
  -1};


struct ActionStruct GrammarLalrActionArray0[9+1] = {
  {3,1,1},
  {4,1,2},
  {15,1,3},
  {17,3,4},
  {18,3,5},
  {19,3,6},
  {20,3,7},
  {21,3,8},
  {22,3,9},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray1[3+1] = {
  {4,1,2},
  {15,1,3},
  {22,3,10},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray2[8+1] = {
  {3,1,1},
  {4,1,2},
  {15,1,3},
  {17,3,4},
  {18,3,11},
  {19,3,6},
  {20,3,7},
  {22,3,9},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray3[12+1] = {
  {0,2,16},
  {3,2,16},
  {5,2,16},
  {6,2,16},
  {7,2,16},
  {8,2,16},
  {9,2,16},
  {10,2,16},
  {11,2,16},
  {12,2,16},
  {13,2,16},
  {14,2,16},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray4[10+1] = {
  {3,1,12},
  {8,1,13},
  {0,2,7},
  {5,2,7},
  {9,2,7},
  {10,2,7},
  {11,2,7},
  {12,2,7},
  {13,2,7},
  {14,2,7},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray5[7+1] = {
  {9,1,14},
  {10,1,15},
  {11,1,16},
  {12,1,17},
  {13,1,18},
  {14,1,19},
  {0,2,0},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray6[12+1] = {
  {6,1,20},
  {7,1,21},
  {0,2,10},
  {3,2,10},
  {5,2,10},
  {8,2,10},
  {9,2,10},
  {10,2,10},
  {11,2,10},
  {12,2,10},
  {13,2,10},
  {14,2,10},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray7[12+1] = {
  {0,2,13},
  {3,2,13},
  {5,2,13},
  {6,2,13},
  {7,2,13},
  {8,2,13},
  {9,2,13},
  {10,2,13},
  {11,2,13},
  {12,2,13},
  {13,2,13},
  {14,2,13},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray8[1+1] = {
  {0,4,0},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray9[12+1] = {
  {0,2,15},
  {3,2,15},
  {5,2,15},
  {6,2,15},
  {7,2,15},
  {8,2,15},
  {9,2,15},
  {10,2,15},
  {11,2,15},
  {12,2,15},
  {13,2,15},
  {14,2,15},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray10[12+1] = {
  {0,2,14},
  {3,2,14},
  {5,2,14},
  {6,2,14},
  {7,2,14},
  {8,2,14},
  {9,2,14},
  {10,2,14},
  {11,2,14},
  {12,2,14},
  {13,2,14},
  {14,2,14},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray11[7+1] = {
  {5,1,22},
  {9,1,14},
  {10,1,15},
  {11,1,16},
  {12,1,17},
  {13,1,18},
  {14,1,19},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray12[6+1] = {
  {3,1,1},
  {4,1,2},
  {15,1,3},
  {19,3,23},
  {20,3,7},
  {22,3,9},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray13[6+1] = {
  {3,1,1},
  {4,1,2},
  {15,1,3},
  {19,3,24},
  {20,3,7},
  {22,3,9},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray14[7+1] = {
  {3,1,1},
  {4,1,2},
  {15,1,3},
  {17,3,25},
  {19,3,6},
  {20,3,7},
  {22,3,9},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray15[7+1] = {
  {3,1,1},
  {4,1,2},
  {15,1,3},
  {17,3,26},
  {19,3,6},
  {20,3,7},
  {22,3,9},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray16[7+1] = {
  {3,1,1},
  {4,1,2},
  {15,1,3},
  {17,3,27},
  {19,3,6},
  {20,3,7},
  {22,3,9},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray17[7+1] = {
  {3,1,1},
  {4,1,2},
  {15,1,3},
  {17,3,28},
  {19,3,6},
  {20,3,7},
  {22,3,9},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray18[7+1] = {
  {3,1,1},
  {4,1,2},
  {15,1,3},
  {17,3,29},
  {19,3,6},
  {20,3,7},
  {22,3,9},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray19[7+1] = {
  {3,1,1},
  {4,1,2},
  {15,1,3},
  {17,3,30},
  {19,3,6},
  {20,3,7},
  {22,3,9},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray20[5+1] = {
  {3,1,1},
  {4,1,2},
  {15,1,3},
  {20,3,31},
  {22,3,9},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray21[5+1] = {
  {3,1,1},
  {4,1,2},
  {15,1,3},
  {20,3,32},
  {22,3,9},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray22[12+1] = {
  {0,2,17},
  {3,2,17},
  {5,2,17},
  {6,2,17},
  {7,2,17},
  {8,2,17},
  {9,2,17},
  {10,2,17},
  {11,2,17},
  {12,2,17},
  {13,2,17},
  {14,2,17},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray23[12+1] = {
  {6,1,20},
  {7,1,21},
  {0,2,9},
  {3,2,9},
  {5,2,9},
  {8,2,9},
  {9,2,9},
  {10,2,9},
  {11,2,9},
  {12,2,9},
  {13,2,9},
  {14,2,9},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray24[12+1] = {
  {6,1,20},
  {7,1,21},
  {0,2,8},
  {3,2,8},
  {5,2,8},
  {8,2,8},
  {9,2,8},
  {10,2,8},
  {11,2,8},
  {12,2,8},
  {13,2,8},
  {14,2,8},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray25[10+1] = {
  {3,1,12},
  {8,1,13},
  {0,2,2},
  {5,2,2},
  {9,2,2},
  {10,2,2},
  {11,2,2},
  {12,2,2},
  {13,2,2},
  {14,2,2},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray26[10+1] = {
  {3,1,12},
  {8,1,13},
  {0,2,3},
  {5,2,3},
  {9,2,3},
  {10,2,3},
  {11,2,3},
  {12,2,3},
  {13,2,3},
  {14,2,3},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray27[10+1] = {
  {3,1,12},
  {8,1,13},
  {0,2,6},
  {5,2,6},
  {9,2,6},
  {10,2,6},
  {11,2,6},
  {12,2,6},
  {13,2,6},
  {14,2,6},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray28[10+1] = {
  {3,1,12},
  {8,1,13},
  {0,2,5},
  {5,2,5},
  {9,2,5},
  {10,2,5},
  {11,2,5},
  {12,2,5},
  {13,2,5},
  {14,2,5},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray29[10+1] = {
  {3,1,12},
  {8,1,13},
  {0,2,1},
  {5,2,1},
  {9,2,1},
  {10,2,1},
  {11,2,1},
  {12,2,1},
  {13,2,1},
  {14,2,1},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray30[10+1] = {
  {3,1,12},
  {8,1,13},
  {0,2,4},
  {5,2,4},
  {9,2,4},
  {10,2,4},
  {11,2,4},
  {12,2,4},
  {13,2,4},
  {14,2,4},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray31[12+1] = {
  {0,2,11},
  {3,2,11},
  {5,2,11},
  {6,2,11},
  {7,2,11},
  {8,2,11},
  {9,2,11},
  {10,2,11},
  {11,2,11},
  {12,2,11},
  {13,2,11},
  {14,2,11},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray32[12+1] = {
  {0,2,12},
  {3,2,12},
  {5,2,12},
  {6,2,12},
  {7,2,12},
  {8,2,12},
  {9,2,12},
  {10,2,12},
  {11,2,12},
  {12,2,12},
  {13,2,12},
  {14,2,12},
  {-1,-1,-1}};



/*
struct SymbolStruct {
  short Kind;
  char *Name;
  };
*/
struct SymbolStruct GrammarSymbolArray[23] = {
  /*  0 */   {3,"EOF"},
  /*  1 */   {7,"Error"},
  /*  2 */   {2,"Whitespace"},
  /*  3 */   {1,"-"},
  /*  4 */   {1,"("},
  /*  5 */   {1,")"},
  /*  6 */   {1,"*"},
  /*  7 */   {1,"/"},
  /*  8 */   {1,"+"},
  /*  9 */   {1,"<"},
  /* 10 */   {1,"<="},
  /* 11 */   {1,"<>"},
  /* 12 */   {1,"=="},
  /* 13 */   {1,">"},
  /* 14 */   {1,">="},
  /* 15 */   {1,"Identifier"},
  /* 16 */   {1,"StringLiteral"},
  /* 17 */   {0,"Add Exp"},
  /* 18 */   {0,"Expression"},
  /* 19 */   {0,"Mult Exp"},
  /* 20 */   {0,"Negate Exp"},
  /* 21 */   {0,"Program"},
  /* 22 */   {0,"Value"} 
  };



/*
struct DfaEdgeStruct {
  int TargetState;
  char *CharacterSet;
  };
struct DfaStateStruct {
  int AcceptSymbol;
  int EdgeCount;
  struct DfaEdgeStruct *Edges;
  };
*/
struct DfaStateStruct GrammarDfaStateArray[22+1] = {
  /* 0 */    {-1,12,GrammarDfaEdgeArray0},
  /* 1 */    {2,1,GrammarDfaEdgeArray1},
  /* 2 */    {3,0,GrammarDfaEdgeArray2},
  /* 3 */    {4,0,GrammarDfaEdgeArray3},
  /* 4 */    {5,0,GrammarDfaEdgeArray4},
  /* 5 */    {6,0,GrammarDfaEdgeArray5},
  /* 6 */    {7,0,GrammarDfaEdgeArray6},
  /* 7 */    {8,0,GrammarDfaEdgeArray7},
  /* 8 */    {-1,1,GrammarDfaEdgeArray8},
  /* 9 */    {12,0,GrammarDfaEdgeArray9},
  /* 10 */    {15,1,GrammarDfaEdgeArray10},
  /* 11 */    {15,1,GrammarDfaEdgeArray11},
  /* 12 */    {-1,3,GrammarDfaEdgeArray12},
  /* 13 */    {-1,3,GrammarDfaEdgeArray13},
  /* 14 */    {-1,1,GrammarDfaEdgeArray14},
  /* 15 */    {-1,3,GrammarDfaEdgeArray15},
  /* 16 */    {16,0,GrammarDfaEdgeArray16},
  /* 17 */    {9,2,GrammarDfaEdgeArray17},
  /* 18 */    {10,0,GrammarDfaEdgeArray18},
  /* 19 */    {11,0,GrammarDfaEdgeArray19},
  /* 20 */    {13,1,GrammarDfaEdgeArray20},
  /* 21 */    {14,0,GrammarDfaEdgeArray21},
  {-1,-1,NULL}};



/*
struct RuleStruct {
  int Head;
  int SymbolsCount;
  int *Symbols;
  char *Description;
  };
*/
struct RuleStruct GrammarRuleArray[18] = {
  /*  0 */   {21,1,GrammarRuleSymbolArray0,"<Program> ::= <Expression>"},
  /*  1 */   {18,3,GrammarRuleSymbolArray1,"<Expression> ::= <Expression> '>' <Add Exp>"},
  /*  2 */   {18,3,GrammarRuleSymbolArray2,"<Expression> ::= <Expression> '<' <Add Exp>"},
  /*  3 */   {18,3,GrammarRuleSymbolArray3,"<Expression> ::= <Expression> '<=' <Add Exp>"},
  /*  4 */   {18,3,GrammarRuleSymbolArray4,"<Expression> ::= <Expression> '>=' <Add Exp>"},
  /*  5 */   {18,3,GrammarRuleSymbolArray5,"<Expression> ::= <Expression> '==' <Add Exp>"},
  /*  6 */   {18,3,GrammarRuleSymbolArray6,"<Expression> ::= <Expression> '<>' <Add Exp>"},
  /*  7 */   {18,1,GrammarRuleSymbolArray7,"<Expression> ::= <Add Exp>"},
  /*  8 */   {17,3,GrammarRuleSymbolArray8,"<Add Exp> ::= <Add Exp> '+' <Mult Exp>"},
  /*  9 */   {17,3,GrammarRuleSymbolArray9,"<Add Exp> ::= <Add Exp> '-' <Mult Exp>"},
  /* 10 */   {17,1,GrammarRuleSymbolArray10,"<Add Exp> ::= <Mult Exp>"},
  /* 11 */   {19,3,GrammarRuleSymbolArray11,"<Mult Exp> ::= <Mult Exp> '*' <Negate Exp>"},
  /* 12 */   {19,3,GrammarRuleSymbolArray12,"<Mult Exp> ::= <Mult Exp> '/' <Negate Exp>"},
  /* 13 */   {19,1,GrammarRuleSymbolArray13,"<Mult Exp> ::= <Negate Exp>"},
  /* 14 */   {20,2,GrammarRuleSymbolArray14,"<Negate Exp> ::= '-' <Value>"},
  /* 15 */   {20,1,GrammarRuleSymbolArray15,"<Negate Exp> ::= <Value>"},
  /* 16 */   {22,1,GrammarRuleSymbolArray16,"<Value> ::= Identifier"},
  /* 17 */   {22,3,GrammarRuleSymbolArray17,"<Value> ::= '(' <Expression> ')'"} 
  };



/*
struct ActionStruct {
  int Entry;
  short Action;
  int Target;
  };
struct LalrStateStruct {
  int ActionCount;
  struct ActionStruct *Actions;
  };
*/
struct LalrStateStruct GrammarLalrStateArray[33+1] = {
  /* 0 */   {9,GrammarLalrActionArray0},
  /* 1 */   {3,GrammarLalrActionArray1},
  /* 2 */   {8,GrammarLalrActionArray2},
  /* 3 */   {12,GrammarLalrActionArray3},
  /* 4 */   {10,GrammarLalrActionArray4},
  /* 5 */   {7,GrammarLalrActionArray5},
  /* 6 */   {12,GrammarLalrActionArray6},
  /* 7 */   {12,GrammarLalrActionArray7},
  /* 8 */   {1,GrammarLalrActionArray8},
  /* 9 */   {12,GrammarLalrActionArray9},
  /* 10 */   {12,GrammarLalrActionArray10},
  /* 11 */   {7,GrammarLalrActionArray11},
  /* 12 */   {6,GrammarLalrActionArray12},
  /* 13 */   {6,GrammarLalrActionArray13},
  /* 14 */   {7,GrammarLalrActionArray14},
  /* 15 */   {7,GrammarLalrActionArray15},
  /* 16 */   {7,GrammarLalrActionArray16},
  /* 17 */   {7,GrammarLalrActionArray17},
  /* 18 */   {7,GrammarLalrActionArray18},
  /* 19 */   {7,GrammarLalrActionArray19},
  /* 20 */   {5,GrammarLalrActionArray20},
  /* 21 */   {5,GrammarLalrActionArray21},
  /* 22 */   {12,GrammarLalrActionArray22},
  /* 23 */   {12,GrammarLalrActionArray23},
  /* 24 */   {12,GrammarLalrActionArray24},
  /* 25 */   {10,GrammarLalrActionArray25},
  /* 26 */   {10,GrammarLalrActionArray26},
  /* 27 */   {10,GrammarLalrActionArray27},
  /* 28 */   {10,GrammarLalrActionArray28},
  /* 29 */   {10,GrammarLalrActionArray29},
  /* 30 */   {10,GrammarLalrActionArray30},
  /* 31 */   {12,GrammarLalrActionArray31},
  /* 32 */   {12,GrammarLalrActionArray32},
  {-1,NULL}};



/*
struct GrammarStruct {
  char CaseSensitive;
  int InitialSymbol;
  int InitialDfaState;
  int InitialLalrState;
  int SymbolCount;
  struct SymbolStruct *SymbolArray;
  int RuleCount;
  struct RuleStruct *RuleArray;
  int DfaStateCount;
  struct DfaStateStruct *DfaArray;
  int LalrStateCount;
  struct LalrStateStruct *LalrArray;
  };
*/
struct GrammarStruct Grammar = {
  /* CaseSensitive */      False,
  /* InitialSymbol */      21,
  /* InitialDfaState */    0,
  /* InitialLalrState */   0,
  /* SymbolCount */        23,
  /* SymbolArray */        GrammarSymbolArray,
  /* RuleCount */          18,
  /* RuleArray */          GrammarRuleArray,
  /* DfaStateCount */      22,
  /* DfaArray */           GrammarDfaStateArray,
  /* LalrStateCount */     33,
  /* LalrArray */          GrammarLalrStateArray
  };
